### ISSUE TITLE
Verify Ownership via DNS Record - Google Search Console

### ISSUE THREAD

**Issue by cedricwaxwing** [dOrgTech/landing-page-v3#71]

**Comment by Dolivero8** [comment]
google-site-verification=H9zyJ2er4tLh6lPIcdv38tevvuCsJuGgxNeebZ5Gr0o



![Image](https://user-images.githubusercontent.com/98119581/198223723-17722b24-54e0-4645-b0af-3392d06eff11.png)

**Comment by juliopavila** [comment]
Done @Dolivero8 

![image](https://user-images.githubusercontent.com/19823989/198365725-3ae1822c-f85c-475a-b62a-9e358b97a05d.png)
