### ISSUE TITLE
Modify Meta Description

### ISSUE THREAD

**Issue by Dolivero8** [dOrgTech/landing-page-v3#77]

**Comment by Dolivero8** [comment]
Meta Description should contain between 70 and 160 characters - spaces included (600 - 940 pixels). - Current Meta Description length: 50 characters.

This description should include most important keywords 

web3 dapp
web3 launch
web3j docs
web3 labs
web3 jobs

**Comment by cedricwaxwing** [comment]
@Dolivero8 how much sense does this description need to make? Trying to combine all of these "web3" keywords into one meaningful description that's less than 160 characters is probably not possible, but if it can just be a little non-sensical, maybe something like this would work:

```
Looking to launch your next web3 dapp? dOrg's web3 labs will bring your ideas to life. If you're a web3 builder looking for web3 jobs, you can find out more in our docs.
```

**Comment by Dolivero8** [comment]
Hey Colin! Yeah this works for me

Thanks

Best,

Diego

**Comment by Joshua-Jack** [comment]
Can I have some clarity on where this needs to be placed? @Dolivero8

**Comment by Dolivero8** [comment]
Hey @Joshua-Jack they should be in the head section of a web page. The meta descriptions should be around 160 characters long.

A properly implemented meta description in the HTML <head> looks like this:

<meta name=”description” content=”A short description of what your page is about. Be as descriptive as possible while staying concise.”>



![Image](https://user-images.githubusercontent.com/98119581/203007890-8bf6c36b-2c20-4543-b3ee-bd53006bf588.png)
