### ISSUE TITLE
Implement WooRank’s Assistant code snippet

### ISSUE THREAD

**Issue by Dolivero8** [dOrgTech/landing-page-v3#83]
<script type="text/javascript">
  window.woorankAssistantOptions = window.woorankAssistantOptions || {};
  window.woorankAssistantOptions.url = 'dorg.tech';
  window.woorankAssistantOptions.assistantPublicKey = '5a2b043aef63db22bd545165d0a06442d925cb10';
  window.woorankAssistantOptions.collectWebVitals = true;
  (function() {
    var wl = document.createElement('script'); wl.type = 'text/javascript'; wl.async = true;
    wl.src = 'https://assistant.woorank.com/hydra/assistantLoader.latest.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(wl, s);
  })();
</script>

**Comment by Dolivero8** [comment]
Install WooRank Asisstant code snipet for further SEO analysis

**Comment by Joshua-Jack** [comment]
This tasks is done. As soon as the PR for GTM is merged I can submit the script. @Dolivero8
