### ISSUE TITLE
Add XML Sitemap

### ISSUE THREAD

**Issue by Dolivero8** [dOrgTech/landing-page-v3#84]

**Comment by Dolivero8** [comment]
Specifying the location of your XML Sitemaps in your robots.txt file ensures that search engines and other crawlers find and access it easily each time they access your website.

Links of interest

What is an XML Sitemap?:  https://www.woorank.com/en/edu/seo-guides/xml-sitemaps

How To Add Your Sitemap To Your Robots.txt File: https://www.woorank.com/en/blog/how-to-locate-a-sitemap-in-a-robots-txt-file

**Comment by Joshua-Jack** [comment]
Okay perfect, I have the sitemap done essentially. The last questions will be the following, 
Do we want to add priority for each page? 
Do we want to add change frequency to each page?

@juliopavila @cedricwaxwing @Dolivero8
