### ISSUE TITLE
Install Google Tag Manager Snippet

### ISSUE THREAD

**Issue by Dolivero8** [dOrgTech/landing-page-v3#89]

**Comment by Dolivero8** [comment]
Paste this code as high in the <head> of the page as possible:


<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PCF3T3M');</script>


Additionally, paste this code immediately after the opening <body> tag:


<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PCF3T3M"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by Joshua-Jack** [comment]
Can I suggest we set up GTM in this following way?

Install react-gtm-module

From there we do something like

const gtmId = what ever the gtm id is;
   const args: TagManagerArgs = { gtmId };
   useEffect(() => {
      TagManager.initialize(args);
   }, []);

**Comment by Joshua-Jack** [comment]
https://github.com/dOrgTech/landing-page-v3/pull/90

Here is the PR we need to add the following env variable to the deployment for this to work correctly. 

Env Variable:  REACT_APP_GTM_ID = GTM-PCF3T3M
